# Generated by Django 3.2.6 on 2022-01-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='الجهاز')),
            ],
            options={
                'verbose_name_plural': 'نوع الجهاز',
            },
        ),
        migrations.CreateModel(
            name='Edara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='كود الادارة')),
                ('name', models.CharField(max_length=15, verbose_name='الادارة')),
            ],
            options={
                'verbose_name_plural': 'الادارة',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='كود المحافظة')),
                ('name', models.CharField(max_length=15, verbose_name='المحافظة')),
            ],
            options={
                'verbose_name_plural': 'المحافظة',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='الماركة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device')),
            ],
            options={
                'verbose_name_plural': 'الماركة',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('national_id', models.IntegerField(max_length=14)),
                ('phone', models.IntegerField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'البيانات الشخصية ',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=15, verbose_name='الوحدة')),
                ('edara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.edara')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.governorate')),
            ],
            options={
                'verbose_name_plural': 'الوحدة',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='الموديل')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mark')),
            ],
            options={
                'verbose_name_plural': 'الموديل',
            },
        ),
        migrations.AddField(
            model_name='edara',
            name='govern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.governorate', verbose_name='محافظة'),
        ),
    ]
