# Generated by Django 3.2.6 on 2022-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalData',
        ),
    ]
