# Generated by Django 3.2.6 on 2022-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_personaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('national_id', models.IntegerField(max_length=14)),
                ('phone', models.IntegerField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'البيانات الشخصية ',
            },
        ),
    ]
