# Generated by Django 3.2.6 on 2022-02-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.IntegerField(verbose_name=' كود الوحدة '),
        ),
        migrations.AlterField(
            model_name='unit',
            name='edara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.edara', verbose_name='الادارة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.governorate', verbose_name='المحافظة'),
        ),
    ]
