# Generated by Django 3.2.6 on 2022-02-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrict',
            name='edara',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.edara'),
            preserve_default=False,
        ),
    ]
