# Generated by Django 3.2.6 on 2022-02-05 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_restrict_edara'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrict',
            name='place',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrict',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.unit'),
            preserve_default=False,
        ),
    ]
