# Generated by Django 3.2.6 on 2022-02-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220205_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrict',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrict',
            name='mark',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrict',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrict',
            name='national_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.personaldata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrict',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
