# Generated by Django 3.2.6 on 2022-02-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220205_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrict',
            name='national_id',
            field=models.IntegerField(max_length=14),
        ),
    ]
