# Generated by Django 3.2.6 on 2022-02-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_restrict_national_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restrict',
            new_name='Place',
        ),
    ]
