# Generated by Django 3.2.6 on 2022-02-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_restrict_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='name',
        ),
    ]
