# Generated by Django 3.2.6 on 2022-02-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_place_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='serial',
            field=models.IntegerField(),
        )
 
    ]
