# Generated by Django 3.2.6 on 2022-02-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220219_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('national_id', models.IntegerField(max_length=14)),
                ('name', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device')),
                ('edara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.edara')),
                ('govern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.governorate')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.model')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.place')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unit')),
            ],
        ),
    ]
