# Generated by Django 3.2.6 on 2022-02-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='datatime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
