# Generated by Django 3.2.6 on 2022-02-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_request_datatime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mark',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.mark'),
            preserve_default=False,
        ),
    ]
